# Setup
title: Nievs
tagline: A Jekyll Theme
baseurl: /nievs
author: Sveinchen

# Permalinks
permalink: /:year/:month/:day/:title.html

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed

# Plugins
plugins:
  - jekyll-gist
